-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/CentralAuth/schema/abstractSchemaChanges/patch-drop-gu_hidden.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX gu_name;
DROP  INDEX gu_email;
DROP  INDEX gu_locked;
DROP  INDEX gu_hidden;
DROP  INDEX gu_hidden_level;
CREATE TEMPORARY TABLE /*_*/__temp__globaluser AS
SELECT  gu_id,  gu_name,  gu_home_db,  gu_email,  gu_email_authenticated,  gu_salt,  gu_password,  gu_locked,  gu_hidden_level,  gu_registration,  gu_password_reset_key,  gu_password_reset_expiration,  gu_auth_token,  gu_cas_token
FROM  /*_*/globaluser;
DROP  TABLE  /*_*/globaluser;
CREATE TABLE  /*_*/globaluser (    gu_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,    gu_name BLOB DEFAULT NULL, gu_home_db BLOB DEFAULT NULL,    gu_email BLOB DEFAULT NULL, gu_email_authenticated BLOB DEFAULT NULL,    gu_salt BLOB DEFAULT NULL, gu_password BLOB DEFAULT NULL,    gu_locked SMALLINT DEFAULT 0 NOT NULL,    gu_hidden_level INTEGER DEFAULT 0 NOT NULL,    gu_registration BLOB DEFAULT NULL,    gu_password_reset_key BLOB DEFAULT NULL,    gu_password_reset_expiration BLOB DEFAULT NULL,    gu_auth_token BLOB DEFAULT NULL, gu_cas_token INTEGER UNSIGNED DEFAULT 1 NOT NULL  );
INSERT INTO  /*_*/globaluser (    gu_id, gu_name, gu_home_db, gu_email,    gu_email_authenticated, gu_salt,    gu_password, gu_locked, gu_hidden_level,    gu_registration, gu_password_reset_key,    gu_password_reset_expiration, gu_auth_token,    gu_cas_token  )
SELECT  gu_id,  gu_name,  gu_home_db,  gu_email,  gu_email_authenticated,  gu_salt,  gu_password,  gu_locked,  gu_hidden_level,  gu_registration,  gu_password_reset_key,  gu_password_reset_expiration,  gu_auth_token,  gu_cas_token
FROM  /*_*/__temp__globaluser;
DROP  TABLE /*_*/__temp__globaluser;
CREATE UNIQUE INDEX gu_name ON  /*_*/globaluser (gu_name);
CREATE INDEX gu_email ON  /*_*/globaluser (gu_email);
CREATE INDEX gu_locked ON  /*_*/globaluser (gu_name, gu_locked);
CREATE INDEX gu_hidden_level ON  /*_*/globaluser (gu_name, gu_hidden_level);