-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: CentralAuth/schema/abstractSchemaChanges/patch-add-uas_year.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX `primary` ON /*_*/global_user_autocreate_serial;
ALTER TABLE /*_*/global_user_autocreate_serial
  ADD uas_year SMALLINT UNSIGNED NOT NULL;
ALTER TABLE /*_*/global_user_autocreate_serial
  ADD PRIMARY KEY (uas_shard, uas_year);
